@host = http://localhost:5103
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImQxM2d1MW4iLCJlbWFpbCI6ImQxM2d1MW5AbG9jYWxob3N0Iiwicm9sZSI6WyJBZG1pbmlzdHJhdG9yIiwiT3RoZXJSb2xlIl0sIm5iZiI6MTc2OTcxMjUyOSwiZXhwIjoxNzcwMzE3MzI5LCJpYXQiOjE3Njk3MTI1MjksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.PXDUFbGYfeKo55K2GRsdLwVqGaMXrPf3VG6FdPfXVB4

### Get JWT Token
POST {{host}}/api/token
Content-Type: application/json

{
    "userName": "d13gu1n",
    "password": "admin"
}

### Claims
GET {{host}}/api/claims
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Products
GET {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{jwt}}
